name: first_hidden_app
description: "First Hidden Bot Flutter App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.6
  web_socket_channel: ^2.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  photo_view: ^0.14.0        # برای زوم روی تصاویر
  path_provider: ^2.1.1
  image: ^4.0.17
  flutter_local_notifications: ^16.3.0
  cached_network_image: ^3.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
